/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.japo.java.forms;

/**
 *
 * @author AnhTu
 */
public class About extends javax.swing.JDialog {

  private static final long serialVersionUID = 1L;

    /**
     * Creates new form DialogDemo
   * @param parent
   * @param modal
     */
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    copyrightTextArea = new javax.swing.JTextArea();
    jLabel1 = new javax.swing.JLabel();
    copyrightTextArea1 = new javax.swing.JTextArea();
    jPanel1 = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();

    copyrightTextArea.setEditable(false);
    copyrightTextArea.setBackground(javax.swing.UIManager.getDefaults().getColor("Panel.background"));
    copyrightTextArea.setColumns(25);
    copyrightTextArea.setLineWrap(true);
    copyrightTextArea.setRows(8);
    copyrightTextArea.setText("Anagrams\n\nCopyright (c) 2003  Irritable Enterprises, Inc.");
    copyrightTextArea.setWrapStyleWord(true);
    copyrightTextArea.setBorder(null);
    copyrightTextArea.setFocusable(false);

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setBackground(new java.awt.Color(255, 255, 255));
    setUndecorated(true);

    jLabel1.setBackground(new java.awt.Color(255, 204, 51));
    jLabel1.setFont(new java.awt.Font("Consolas", 1, 48)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 255, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("About");
    getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

    copyrightTextArea1.setEditable(false);
    copyrightTextArea1.setBackground(new java.awt.Color(255, 255, 255));
    copyrightTextArea1.setColumns(25);
    copyrightTextArea1.setForeground(new java.awt.Color(102, 102, 102));
    copyrightTextArea1.setLineWrap(true);
    copyrightTextArea1.setRows(8);
    copyrightTextArea1.setText("\n>> La CalculaCutre - mon_mo | 2020\n\n            Va a pedales...!\n\n        Signifique lo que signifique :)");
    copyrightTextArea1.setWrapStyleWord(true);
    copyrightTextArea1.setBorder(null);
    copyrightTextArea1.setFocusable(false);
    getContentPane().add(copyrightTextArea1, java.awt.BorderLayout.PAGE_END);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    jButton1.setBackground(new java.awt.Color(102, 102, 102));
    jButton1.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
    jButton1.setText("Close");
    jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    jPanel1.add(jButton1);

    getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea copyrightTextArea;
  private javax.swing.JTextArea copyrightTextArea1;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
