/* 
 * Copyright (C) 2020 mon_mode   0mon.mode@gmail.com
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package org.japo.java.forms;

import java.awt.Color;
import java.sql.SQLException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.swing.JOptionPane;
import org.japo.java.entities.Login;
import org.japo.java.entities.LoginDao;
import org.japo.java.libraries.UtilesSwing;

/**
 *
 * @author monmo
 */
public class GUI extends javax.swing.JFrame {

  private static final long serialVersionUID = 1L;

  // Referencias
  private final Properties prp;

  private boolean checkbox = false;
  private int cont = 0;

  private final Color myGray = new Color(187, 187, 187);

  public GUI(Properties prp) {
    // Conectar Referencia
    this.prp = prp;

    // Inicialización Anterior
    initBefore();

    // Creación Interfaz
    initComponents();

    // Inicializacion Posterior
    initAfter();
  }
// Inicialización Anterior    

  private void initBefore() {
    // Establecer LnF
    UtilesSwing.establecerLnFProfile(prp.getProperty("look_and_feel_profile"));

  }

  // Inicialización Posterior
  private void initAfter() {
    // Establecer Favicon
    UtilesSwing.establecerFavicon(this, prp.getProperty("img_favicon_resource"));

    // Ventana Principal
    setTitle(prp.getProperty("form_title"));
    int width = Integer.parseInt(prp.getProperty("form_width"));
    int height = Integer.parseInt(prp.getProperty("form_height"));
    setSize(width, height);
    setLocationRelativeTo(null);

    jAvatar.requestFocus();

    //pone color gris a los jText
    jTextUser.setForeground(myGray);
    jPassword.setForeground(myGray);
  }

  private void startAuthent() throws SQLException, ServletException {
    LoginDao ld = new LoginDao(prp);
//    
//    LoginServlet ls = new LoginServlet();
//   ls.init(ls);
    String pass;
    char getpass[];

    getpass = jPassword.getPassword();
    pass = String.valueOf(getpass);

      //test de lo que imprime como pass.
//    System.out.println(pass);
//    System.out.println(pass.toCharArray());
//    si el login es ok
    if (ld.newAuthentiUser(new Login(jTextUser.getText(), pass.toCharArray()))) {
      System.out.println("OLé!");
      System.out.println();
    } else {  //si falla el login, completar
      System.out.println("UN cagarro, fin.");
    }

  }

  private void activaCheckbox() {

    if (checkbox == false && cont < 3) {
      cont++;

      switch (cont) {
        case 1:
          JOptionPane.showMessageDialog(this, "Esto no hace nada, ni lo toques, primer aviso!");
          break;
        case 2:
          JOptionPane.showMessageDialog(this, "UYYYY, SEGUNDO AVISO, eeee!");
          break;
        case 3:
          JOptionPane.showMessageDialog(this, "ALE POR CHECHU que eres!, Al carrer!");
          break;
      }
      if (cont > 3) {
        checkbox = true;
      }
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jAvatar = new javax.swing.JPanel();
    jImage = new javax.swing.JLabel();
    jLoginPanel = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jTextUser = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jButton1 = new javax.swing.JButton();
    jCheckBox1 = new javax.swing.JCheckBox();
    jPassword = new javax.swing.JPasswordField();
    jCancelPanel = new javax.swing.JPanel();
    jButton2 = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(204, 204, 204));

    jAvatar.setBackground(new java.awt.Color(232, 230, 209));
    jAvatar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jImage.setIcon(new javax.swing.ImageIcon("/Users/Jonsui/Documents/plantillas_daw/DAWapocaliptico/LMYSGI/099-LoginPlantilla/img/img_avatar.png")); // NOI18N
    jImage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
    jAvatar.add(jImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

    jLoginPanel.setBackground(new java.awt.Color(232, 230, 209));

    jLabel1.setBackground(new java.awt.Color(232, 230, 209));
    jLabel1.setForeground(new java.awt.Color(0, 0, 0));
    jLabel1.setText("User");

    jTextUser.setBackground(new java.awt.Color(255, 255, 255));
    jTextUser.setHorizontalAlignment(javax.swing.JTextField.LEFT);
    jTextUser.setText("  Enter User");
    jTextUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 3, 5, 5));
    jTextUser.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        jTextUserFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        jTextUserFocusLost(evt);
      }
    });

    jLabel2.setBackground(new java.awt.Color(204, 204, 204));
    jLabel2.setForeground(new java.awt.Color(0, 0, 0));
    jLabel2.setText("Password");

    jButton1.setBackground(new java.awt.Color(232, 230, 209));
    jButton1.setText("Login");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jCheckBox1.setBackground(new java.awt.Color(232, 230, 209));
    jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
    jCheckBox1.setText("Remember me");
    jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseEntered(java.awt.event.MouseEvent evt) {
        jCheckBox1MouseEntered(evt);
      }
    });

    jPassword.setBackground(new java.awt.Color(255, 255, 255));
    jPassword.setText("  jPasswordField1");
    jPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    jPassword.setCaretPosition(4);
    jPassword.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        jPasswordFocusGained(evt);
      }
      public void focusLost(java.awt.event.FocusEvent evt) {
        jPasswordFocusLost(evt);
      }
    });

    javax.swing.GroupLayout jLoginPanelLayout = new javax.swing.GroupLayout(jLoginPanel);
    jLoginPanel.setLayout(jLoginPanelLayout);
    jLoginPanelLayout.setHorizontalGroup(
      jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jPassword)
          .addComponent(jTextUser)
          .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLoginPanelLayout.createSequentialGroup()
            .addGroup(jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
            .addGap(0, 0, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jLoginPanelLayout.setVerticalGroup(
      jLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jLoginPanelLayout.createSequentialGroup()
        .addGap(1, 1, 1)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jTextUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(1, 1, 1)
        .addComponent(jPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );

    jCancelPanel.setBackground(new java.awt.Color(168, 123, 79));

    jButton2.setBackground(new java.awt.Color(168, 123, 79));
    jButton2.setText("Close");

    jLabel3.setForeground(new java.awt.Color(0, 0, 0));
    jLabel3.setText("Forgot Password");

    javax.swing.GroupLayout jCancelPanelLayout = new javax.swing.GroupLayout(jCancelPanel);
    jCancelPanel.setLayout(jCancelPanelLayout);
    jCancelPanelLayout.setHorizontalGroup(
      jCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jCancelPanelLayout.createSequentialGroup()
        .addGap(28, 28, 28)
        .addComponent(jButton2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel3)
        .addGap(33, 33, 33))
    );
    jCancelPanelLayout.setVerticalGroup(
      jCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jCancelPanelLayout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(jCancelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButton2)
          .addComponent(jLabel3))
        .addContainerGap(36, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jCancelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLoginPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jAvatar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(0, 0, 0))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(0, 0, 0)
        .addComponent(jAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, 0)
        .addComponent(jCancelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jTextUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUserFocusGained
    jTextUser.setText("");
    jTextUser.setForeground(Color.BLACK);
  }//GEN-LAST:event_jTextUserFocusGained

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
      startAuthent();
    } catch (SQLException | ServletException ex) {
      Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_jButton1ActionPerformed

  private void jTextUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUserFocusLost
    if (jTextUser.getText().equals("")) {
      jTextUser.setForeground(myGray);
      jTextUser.setText("Enter User");
    }
  }//GEN-LAST:event_jTextUserFocusLost

  private void jPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusGained
    jPassword.setText("");
    jPassword.setForeground(Color.BLACK);
  }//GEN-LAST:event_jPasswordFocusGained

  private void jPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordFocusLost
    if (jPassword.getPassword().equals("")) {
      jPassword.setForeground(myGray);
      jPassword.setText("Enter User");
    }
  }//GEN-LAST:event_jPasswordFocusLost

  private void jCheckBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseEntered
    activaCheckbox();
  }//GEN-LAST:event_jCheckBox1MouseEntered


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel jAvatar;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JPanel jCancelPanel;
  private javax.swing.JCheckBox jCheckBox1;
  private javax.swing.JLabel jImage;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jLoginPanel;
  private javax.swing.JPasswordField jPassword;
  public static javax.swing.JTextField jTextUser;
  // End of variables declaration//GEN-END:variables
}
